const catalogue={
  AAPL:{name:'Apple',price:213.55,change:.42,cost:213.55},SPCX:{name:'SPAC & New Issue ETF',price:21.84,change:-.46,cost:29.10},LMT:{name:'Lockheed Martin',price:492.31,change:.84,cost:468.20},NVDA:{name:'NVIDIA',price:176.75,change:2.38,cost:121.40},OKLO:{name:'Oklo',price:68.42,change:-3.12,cost:54.80},ORCL:{name:'Oracle',price:244.16,change:1.56,cost:183.50},PLTR:{name:'Palantir',price:153.22,change:3.76,cost:81.25},VOO:{name:'Vanguard S&P 500 ETF',price:590.64,change:.31,cost:532.40},VTI:{name:'Vanguard Total Stock ETF',price:326.18,change:.18,cost:291.70}
};
const defaults=[['AAPL',1],['SPCX',1],['LMT',1],['NVDA',3],['OKLO',1],['ORCL',2],['PLTR',2],['VOO',2],['VTI',2]].map(([symbol,shares])=>({symbol,shares,cost:catalogue[symbol].cost}));
const key='northstar.holdings.v1';let holdings;try{holdings=JSON.parse(localStorage.getItem(key))||defaults}catch(e){holdings=defaults}
const aaplMigrationKey='northstar.portfolio.aapl.v1';if(!localStorage.getItem(aaplMigrationKey)){if(!holdings.some(h=>h.symbol==='AAPL'))holdings.unshift({symbol:'AAPL',shares:1,cost:catalogue.AAPL.cost});localStorage.setItem(key,JSON.stringify(holdings));localStorage.setItem(aaplMigrationKey,'done')}
const savingsKey='northstar.savings.v1';let savings;try{savings=JSON.parse(localStorage.getItem(savingsKey))||{balance:1770.58,rate:3}}catch(e){savings={balance:1770.58,rate:3}}
const $=s=>document.querySelector(s),money=n=>n.toLocaleString('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2}),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const indices=[['S&P 500','6,389.77',.12],['NASDAQ','21,178.58',.33],['DOW','44,837.56',-.14],['VIX','15.08',-1.44]];
const signalData=[{s:'NVDA',label:'Bullish momentum',text:'AI infrastructure demand and the latest platform cycle support the upside case; valuation and export policy remain key risks.',score:78},{s:'OKLO',label:'Event-driven watch',text:'Commercial milestones and energy-policy headlines can create sharp moves. High volatility lowers signal conviction.',score:56},{s:'PLTR',label:'Positive, extended',text:'Recent contract momentum supports growth, while a premium valuation raises pullback risk after strong runs.',score:69}];
const newsData=[['NVDA','AI spending stays central to chip outlook','Earnings theme · Today'],['ORCL','Cloud capacity and database AI demand in focus','Company release · 2h'],['LMT','Defense program awards support backlog visibility','Sector update · 4h'],['OKLO','Advanced nuclear milestones remain key catalyst','Regulatory theme · 6h']];
function stock(s){if(!catalogue[s])catalogue[s]={name:s+' position',price:100,change:0,cost:100};return catalogue[s]}
function spark(s,positive=true){let pts=[];for(let i=0;i<8;i++)pts.push(`${i*10},${12-Math.sin(i*1.4+s.charCodeAt(0))*(positive?5:3)-(positive?i*.5:-i*.25)}`);return `<svg class="spark" viewBox="0 0 70 24"><polyline points="${pts.join(' ')}" fill="none" stroke="${positive?'#0d7b52':'#d35452'}" stroke-width="1.7"/></svg>`}
function render(){const positions=holdings.map(h=>({...h,...stock(h.symbol)}));const value=positions.reduce((a,h)=>a+h.price*h.shares,0),basis=positions.reduce((a,h)=>a+(Number(h.cost)||h.price)*h.shares,0),day=positions.reduce((a,h)=>a+h.price*h.shares*h.change/100,0);$('#portfolioValue').textContent=money(value);$('#sideValue').textContent=money(value+savings.balance);$('#costBasis').textContent=money(basis);setChange($('#dayGain'),day,day/value*100);setChange($('#totalReturn'),value-basis,(value-basis)/basis*100);setChange($('#portfolioChange'),day,day/value*100);
  const savingsYear=savings.balance*Math.pow(1+savings.rate/100,1);$('#indices').innerHTML=indices.map(([n,v,c])=>`<article class="index-card"><div class="index-name"><span>${n}</span><span class="${c>=0?'up':'down'}">${c>=0?'↗':'↘'}</span></div><div class="index-value">${v}</div><span class="change ${c>=0?'up':'down'}">${c>=0?'+':''}${c.toFixed(2)}%</span></article>`).join('')+`<article class="index-card" id="savings-card"><div class="index-name"><span>YOUR SAVINGS</span><span class="up">●</span></div><div class="index-value">${money(savings.balance)}</div><span class="change up">${savings.rate.toFixed(2)}% APY · ${money(savingsYear)} in 1 yr</span></article>`;
  const movers=[...positions].sort((a,b)=>b.change-a.change),selected=[movers[0],movers[movers.length-1]].filter(Boolean);$('#movers').innerHTML=selected.length?selected.map(h=>`<article class="mover"><div class="ticker"><span class="stock-icon">${esc(h.symbol.slice(0,2))}</span><span><b>${esc(h.symbol)}</b><small>${h.change>=0?'Top gainer':'Top decliner'}</small></span></div><div class="mover-price"><strong>${money(h.price)}</strong><span class="pill ${h.change>=0?'up':'down'}">${h.change>=0?'+':''}${h.change.toFixed(2)}%</span></div></article>`).join(''):'<p class="empty">Add a holding to see movers.</p>';
  $('#holdingsRows').innerHTML=positions.length?positions.map((h,i)=>`<tr><td><div class="holding-stock"><span class="stock-icon">${esc(h.symbol.slice(0,2))}</span><span><b>${esc(h.symbol)}</b><small>${esc(h.name)}</small></span></div></td><td class="align-right">${h.shares}</td><td class="align-right"><b>${money(h.price)}</b></td><td><span class="change ${h.change>=0?'up':'down'}">${h.change>=0?'+':''}${h.change.toFixed(2)}%</span></td><td class="align-right"><b>${money(h.price*h.shares)}</b></td><td>${spark(h.symbol,h.change>=0)}</td><td><button class="delete" data-delete="${i}" title="Remove holding">×</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">No holdings yet. Add your first stock to begin.</td></tr>';drawChart(value)}
function setChange(el,amount,pct){el.textContent=`${amount>=0?'+':'−'}${money(Math.abs(amount))} (${amount>=0?'+':'−'}${Math.abs(pct||0).toFixed(2)}%)`;el.className='change '+(amount>=0?'up':'down')}
function drawChart(value){const svg=$('#portfolioChart'),vals=Array.from({length:24},(_,i)=>value*(.925+i*.0037+Math.sin(i*.84)*.008));const min=Math.min(...vals)*.995,max=Math.max(...vals)*1.005,pts=vals.map((v,i)=>`${i/(vals.length-1)*700},${175-(v-min)/(max-min)*145}`).join(' ');svg.innerHTML=`<defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#0d7b52" stop-opacity=".2"/><stop offset="1" stop-color="#0d7b52" stop-opacity="0"/></linearGradient></defs><line x1="0" y1="50" x2="700" y2="50" stroke="#e8ece9"/><line x1="0" y1="110" x2="700" y2="110" stroke="#e8ece9"/><polygon points="0,190 ${pts} 700,190" fill="url(#fill)"/><polyline points="${pts}" fill="none" stroke="#0d7b52" stroke-width="2.5" vector-effect="non-scaling-stroke"/><circle cx="700" cy="${pts.split(' ').at(-1).split(',')[1]}" r="4" fill="#0d7b52"/>`}
$('#signals').innerHTML=signalData.map(x=>`<article class="signal"><div class="signal-top"><h3>${x.s} · ${x.label}</h3><span class="badge ${x.score<60?'watch':''}">${x.score}%</span></div><p>${x.text}</p><div class="confidence"><i style="width:${x.score}%"></i></div><div class="signal-meta"><span>LOWER CONVICTION</span><span>MODEL CONFIDENCE</span></div></article>`).join('');
$('#news').innerHTML=newsData.map(n=>`<article class="news-item"><span class="news-logo">${n[0]}</span><div><h3>${n[1]}</h3><p>${n[2]}</p></div></article>`).join('');
const dialog=$('#holdingDialog'),savingsDialog=$('#savingsDialog');function openDialog(){dialog.showModal();$('#symbol').focus()}$('#addHolding').onclick=openDialog;$('#addHolding2').onclick=openDialog;dialog.querySelectorAll('.close').forEach(b=>b.onclick=()=>dialog.close());dialog.onclick=e=>{if(e.target===dialog)dialog.close()};
$('#holdingForm').onsubmit=e=>{e.preventDefault();const symbol=$('#symbol').value.trim().toUpperCase(),shares=Number($('#shares').value),known=stock(symbol),cost=Number($('#buyPrice').value)||known.price,existing=holdings.find(h=>h.symbol===symbol);if(existing){existing.shares+=shares;existing.cost=((existing.cost*(existing.shares-shares))+(cost*shares))/existing.shares}else holdings.push({symbol,shares,cost});save();render();e.target.reset();dialog.close();toast(`${symbol} added to your portfolio`)};
$('#holdingsRows').onclick=e=>{const i=e.target.dataset.delete;if(i!==undefined){holdings.splice(Number(i),1);save();render();toast('Holding removed')}};function save(){localStorage.setItem(key,JSON.stringify(holdings))}function toast(m){$('#toast').textContent=m;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2100)}
async function updateQuotes(showToast=false){const b=$('#refresh');b.classList.add('refreshing');$('#marketStatus').textContent='Updating live quotes…';let updated=0;try{const symbols=[...new Set(holdings.map(h=>h.symbol))],response=await fetch(`/api/quotes?symbols=${encodeURIComponent(symbols.join(','))}`);if(!response.ok)throw Error('quote service unavailable');const data=await response.json();Object.entries(data.quotes||{}).forEach(([symbol,quote])=>{if(quote.price&&Number.isFinite(quote.change)){const item=stock(symbol);item.price=quote.price;item.change=quote.change;updated++}})}catch(e){/* Retain the last known values when the internet connection is unavailable. */}b.classList.remove('refreshing');render();$('#marketStatus').textContent=updated?`${updated} live quotes · updated now`:'Connection unavailable · last known prices';if(showToast)toast(updated?'Live market prices updated':'Could not reach the market service')}
$('#refresh').onclick=()=>updateQuotes(true);
document.querySelectorAll('.nav button[data-target]').forEach(button=>button.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));button.classList.add('active');const target=$('#'+button.dataset.target);target.scrollIntoView({behavior:'smooth',block:'start'});target.classList.add('section-focus');setTimeout(()=>target.classList.remove('section-focus'),1000)});
$('#preferences').onclick=()=>{$('#savingsBalance').value=savings.balance.toFixed(2);$('#savingsRate').value=savings.rate;document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));$('#preferences').classList.add('active');savingsDialog.showModal()};document.querySelectorAll('.close-savings').forEach(b=>b.onclick=()=>savingsDialog.close());savingsDialog.onclick=e=>{if(e.target===savingsDialog)savingsDialog.close()};$('#savingsForm').onsubmit=e=>{e.preventDefault();savings={balance:Number($('#savingsBalance').value),rate:Number($('#savingsRate').value)};localStorage.setItem(savingsKey,JSON.stringify(savings));render();savingsDialog.close();toast('Savings settings updated')};
$('#indices').onclick=e=>{if(e.target.closest('#savings-card'))$('#preferences').click()};
document.querySelectorAll('.periods button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.periods button').forEach(x=>x.classList.remove('active'));b.classList.add('active');drawChart(holdings.reduce((a,h)=>a+stock(h.symbol).price*h.shares,0));toast(`${b.textContent} view selected`)});$('#dateLine').textContent=new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})+' · Your daily market pulse';render();if(location.protocol==='file:'){$('#launchWarning').classList.add('show');$('#marketStatus').textContent='Open with northstar.cmd for live quotes'}else updateQuotes();
